openapi: 3.0.3
info:
  title: Venue and Show API
  description: CRUD API for managing venues and shows
  version: 1.0.0

servers:
  - url: http://localhost:5000/

paths:
  /api/create_venue:
    post:
      summary: Create a new venue
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                V_name:
                  type: string
                place:
                  type: string
                capacity:
                  type: integer
                rating:
                  type: integer
              
                
      responses:
        '201':
          description: Venue created
        default:
          description: Unexpected error

  /api/all_venues:
    get:
      summary: All venues
      responses:
        '200':
          description: All venues
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
                  example: "venue name"
        default:
          description: Unexpected error

  /api/update_venue/{Venue_id}:
    put:
      summary: Update an existing venue
      parameters:
        - in: path
          name: Venue_id
          required: true
          schema:
            type: integer
          description: Venue_id of the venue to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                V_name:
                  type: string
                place:
                  type: string
                capacity:
                  type: integer
                rating:
                  type: integer
              
      responses:
        '201':
          description: Venue updated
        default:
          description: Unexpected error

  /api/delete_venue/{Venue_id}:
    delete:
      summary: Delete an existing venue
      parameters:
        - in: path
          name: Venue_id
          required: true
          schema:
            type: integer
          description: Venue_id of the venue to delete
      responses:
        '202':
          description: Venue deleted
        default:
          description: Unexpected error

  
  
  /api/create_show:
    post:
      summary: Create a new show
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                S_name:
                  type: string
                rating:
                  type: integer
                tags:
                  type: string
                date:
                  type: string
                time:
                  type: string
                ticketPrice:
                  type: integer
                language:
                  type: string
                type:
                  type: string
                Venue_id:
                  type: integer
                Show_Capacity:
                  type: integer
              
      responses:
        '201':
          description: Show created
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
    
  /api/all_shows:
    get:
      summary: Get all shows
      responses:
        '200':
          description: all shows
          content:
            application/json:
              schema:
                type: object
                properties:
                  shows:
                    type: object
                    additionalProperties:
                      type: string
    
  /api/update_show/{Show_id}:
      put:
        summary: Update a show
        parameters:
          - in: path
            name: Show_id
            schema:
              type: integer
            required: true
            description: Show_id of the show to update
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  S_name:
                    type: string
                  rating:
                    type: integer
                  tags:
                    type: string
                  date:
                    type: string
                  time:
                    type: string
                  ticketPrice:
                    type: integer
                  language:
                    type: string
                  type:
                    type: string
                  Venue_id:
                    type: integer
                  Show_Capacity:
                    type: integer
                
        responses:
          '201':
            description: Show updated
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    status:
                      type: string
  
  /api/delete_show/{Show_id}:
      delete:
        summary: Delete a show
        parameters:
          - in: path
            name: Show_id
            schema:
              type: integer
            required: true
            description: Show_id show to delete
        responses:
          '202':
            description: Show deleted
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    status:
                      type: string